import { StructureLineData, Point2D } from '../types/drawing';

const getDistance = (p1: Point2D, p2: Point2D) => {
  return Math.sqrt(Math.pow(p2.x - p1.x, 2) + Math.pow(p2.y - p1.y, 2));
};

const getAngle = (p1: Point2D, p2: Point2D) => {
  return Math.atan2(p2.y - p1.y, p2.x - p1.x);
};

const getMidpoint = (p1: Point2D, p2: Point2D): Point2D => {
  return { x: (p1.x + p2.x) / 2, y: (p1.y + p2.y) / 2 };
};

export const extractCenterLinesFromWalls = (
  lines: StructureLineData[],
  minThickness: number = 100,
  maxThickness: number = 400,
  angleTolerance: number = 0.05
): StructureLineData[] => {
  const wallLines = lines.filter((l) => l.type === 'WALL' && l.coordinates.length >= 2);
  const centerLines: StructureLineData[] = [];
  const processedIds = new Set<string>();

  for (let i = 0; i < wallLines.length; i++) {
    const lineA = wallLines[i];
    if (processedIds.has(lineA.id)) continue;

    const pA1 = lineA.coordinates[0];
    const pA2 = lineA.coordinates[1];
    const angleA = getAngle(pA1, pA2);

    let bestPair: StructureLineData | null = null;
    let minDiff = Infinity;

    for (let j = i + 1; j < wallLines.length; j++) {
      const lineB = wallLines[j];
      if (processedIds.has(lineB.id)) continue;

      const pB1 = lineB.coordinates[0];
      const pB2 = lineB.coordinates[1];
      const angleB = getAngle(pB1, pB2);

      let angleDiff = Math.abs(angleA - angleB);
      if (angleDiff > Math.PI / 2) {
        angleDiff = Math.PI - angleDiff;
      }

      if (angleDiff > angleTolerance) continue;

      const distStart = getDistance(pA1, pB1);
      const distCross = getDistance(pA1, pB2);
      const currentDist = Math.min(distStart, distCross);

      if (currentDist >= minThickness && currentDist <= maxThickness && currentDist < minDiff) {
        minDiff = currentDist;
        bestPair = lineB;
      }
    }

    if (bestPair) {
      processedIds.add(lineA.id);
      processedIds.add(bestPair.id);

      const pB1 = bestPair.coordinates[0];
      const pB2 = bestPair.coordinates[1];

      const isReversed = getDistance(pA1, pB1) > getDistance(pA1, pB2);
      
      const centerStart = getMidpoint(pA1, isReversed ? pB2 : pB1);
      const centerEnd = getMidpoint(pA2, isReversed ? pB1 : pB2);

      centerLines.push({
        id: `center_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`,
        source: 'CAD',
        type: 'CENTER_LINE',
        coordinates: [centerStart, centerEnd],
        thickness: 2,
        properties: { isAutoGenerated: true },
      });
    }
  }

  return centerLines;
};
