import { StructureLineData, Point2D, StructureType } from '../types/drawing';
import { DxfTransform } from '../store/useDrawingStore';

// 레이어명으로 구조 부재 종류 분류 (대만/동남아/한국 관례 키워드)
const classifyLayer = (name: string): StructureType | null => {
  const u = (name || '').toUpperCase();
  if (/COL|기둥|柱/.test(u)) return 'COLUMN';
  if (/WALL|옹벽|벽|墙|牆|RC/.test(u)) return 'WALL';
  return null;
};

export interface ExtractResult {
  members: StructureLineData[];
  counts: { wall: number; column: number };
  truncated: boolean;
}

/**
 * 보이는 구조 레이어(벽/기둥)의 DXF 엔티티를 편집 가능한 구조 부재(StructureLineData)로 변환한다.
 * - 좌표는 화면(캔버스) 좌표로 변환되어 렌더된 도면과 정확히 겹친다.
 * - LINE/LWPOLYLINE/POLYLINE을 선분 단위로 추출 (ARC/원 등은 추후 보강).
 */
export const extractMembersFromDxf = (
  entities: any[],
  layers: { name: string; visible: boolean }[],
  t: DxfTransform,
  cap: number = 4000,
): ExtractResult => {
  const visible = new Map(layers.map((l) => [l.name, l.visible]));
  const tx = (x: number) => t.pad + (x - t.minX) * t.scale;
  const ty = (y: number) => t.pad + (t.maxY - y) * t.scale;
  const members: StructureLineData[] = [];
  let wall = 0, column = 0, idc = 0, truncated = false;

  const push = (type: StructureType, a: any, b: any) => {
    members.push({
      id: `cad_${Date.now().toString(36)}_${idc++}`,
      source: 'CAD',
      type,
      shape: 'line',
      coordinates: [{ x: tx(a.x), y: ty(a.y) }, { x: tx(b.x), y: ty(b.y) }],
      thickness: type === 'COLUMN' ? 2 : 3,
      properties: { fromCad: true, layer: (a as any)._layer },
    });
  };

  for (const e of entities) {
    if (members.length >= cap) { truncated = true; break; }
    const cls = classifyLayer(e.layer);
    if (!cls) continue;
    if (visible.get(e.layer) === false) continue; // 숨긴 레이어는 제외

    const etype = (e.type || '').toUpperCase();
    const before = members.length;

    if (etype === 'LINE' && Array.isArray(e.vertices) && e.vertices.length >= 2) {
      push(cls, e.vertices[0], e.vertices[1]);
    } else if ((etype === 'LWPOLYLINE' || etype === 'POLYLINE') && Array.isArray(e.vertices) && e.vertices.length >= 2) {
      for (let i = 0; i < e.vertices.length - 1; i++) push(cls, e.vertices[i], e.vertices[i + 1]);
      if (e.shape === true || e.closed === true) push(cls, e.vertices[e.vertices.length - 1], e.vertices[0]);
    }

    if (members.length > before) { cls === 'WALL' ? wall++ : column++; }
  }

  return { members, counts: { wall, column }, truncated };
};

const getDistance = (p1: Point2D, p2: Point2D) => {
  return Math.sqrt(Math.pow(p2.x - p1.x, 2) + Math.pow(p2.y - p1.y, 2));
};

const getAngle = (p1: Point2D, p2: Point2D) => {
  return Math.atan2(p2.y - p1.y, p2.x - p1.x);
};

const getMidpoint = (p1: Point2D, p2: Point2D): Point2D => {
  return { x: (p1.x + p2.x) / 2, y: (p1.y + p2.y) / 2 };
};

export const extractCenterLinesFromWalls = (
  lines: StructureLineData[],
  minThickness: number = 100,
  maxThickness: number = 400,
  angleTolerance: number = 0.05
): StructureLineData[] => {
  const wallLines = lines.filter((l) => l.type === 'WALL' && l.coordinates.length >= 2);
  const centerLines: StructureLineData[] = [];
  const processedIds = new Set<string>();

  for (let i = 0; i < wallLines.length; i++) {
    const lineA = wallLines[i];
    if (processedIds.has(lineA.id)) continue;

    const pA1 = lineA.coordinates[0];
    const pA2 = lineA.coordinates[1];
    const angleA = getAngle(pA1, pA2);

    let bestPair: StructureLineData | null = null;
    let minDiff = Infinity;

    for (let j = i + 1; j < wallLines.length; j++) {
      const lineB = wallLines[j];
      if (processedIds.has(lineB.id)) continue;

      const pB1 = lineB.coordinates[0];
      const pB2 = lineB.coordinates[1];
      const angleB = getAngle(pB1, pB2);

      let angleDiff = Math.abs(angleA - angleB);
      if (angleDiff > Math.PI / 2) {
        angleDiff = Math.PI - angleDiff;
      }

      if (angleDiff > angleTolerance) continue;

      const distStart = getDistance(pA1, pB1);
      const distCross = getDistance(pA1, pB2);
      const currentDist = Math.min(distStart, distCross);

      if (currentDist >= minThickness && currentDist <= maxThickness && currentDist < minDiff) {
        minDiff = currentDist;
        bestPair = lineB;
      }
    }

    if (bestPair) {
      processedIds.add(lineA.id);
      processedIds.add(bestPair.id);

      const pB1 = bestPair.coordinates[0];
      const pB2 = bestPair.coordinates[1];

      const isReversed = getDistance(pA1, pB1) > getDistance(pA1, pB2);
      
      const centerStart = getMidpoint(pA1, isReversed ? pB2 : pB1);
      const centerEnd = getMidpoint(pA2, isReversed ? pB1 : pB2);

      centerLines.push({
        id: `center_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`,
        source: 'CAD',
        type: 'CENTER_LINE',
        coordinates: [centerStart, centerEnd],
        thickness: 2,
        properties: { isAutoGenerated: true },
      });
    }
  }

  return centerLines;
};
